name: TrackExchange
version: ${version}
main: me.pigalala.trackexchange.TrackExchange
api-version: '1.20'
load: STARTUP
depend: [TimingSystem, FastAsyncWorldEdit]
authors: [Pigalala]

commands:
  trackexchange:
    aliases: [tex, tx]

permissions:
  trackexchange.export:
    default: op
  trackexchange.import:
    default: op